accounts:
  global:
    - "" # global-auth
    - "" # global-logging
  project-notifier:
    - "" # dev-project-notifier
    - "" # ver-project-notifier
    - "" # prd-project-notifier
  strava:
    - "" # dev-strava
    
assume_role_policies:
  admin_policy: 
    roles:
      - admin
      - power-user
      - read-only-user
    accounts:
      - global
      - project-notifier
      - strava
  dev_policy: 
    roles:
      - admin
    accounts:
      - project-notifier
  read_only_policy: 
    roles:
      - read-only-user
    accounts:
      - project-notifier
      
iam_groups:
  admins:
    members:
      - admin_1@xpiredmilk.com
      - admin_2@xpiredmilk.com
      - admin_3@xpiredmilk.com
      - admin_4@xpiredmilk.com
      - admin_5@xpiredmilk.com
      - admin_6@xpiredmilk.com
    policies:
      - admin_policy
  devs:
    members:
      - admin_4@xpiredmilk.com
      - admin_5@xpiredmilk.com
      - admin_6@xpiredmilk.com
      - devs_1@xpiredmilk.com
      - devs_2@xpiredmilk.com
      - devs_3@xpiredmilk.com
      - devs_4@xpiredmilk.com
      - devs_5@xpiredmilk.com
    policies:
      - dev_policy
      - read_only_policy